### ISSUE TITLE
New featurizer

### ISSUE THREAD

**Issue by ethancohen123** [datamol-io/molfeat#51]
### Description & Motivation

It seems to be trained on more than any of the featurizer actually present in molfeat

### Is your featurizer open-source ?

- [ ] Yes it's open source

### Are you willing to contribute to the PR for this featurizer ?

- [ ] Yes I'm willing to contribute

### Pitch

Hi,
I just saw this featurizer out there and seems good : https://huggingface.co/entropy/gpt2_zinc_87m
Any chance it might be added to molfeat ? @cwognum @hadim 
Thanks

### Featurizer description

<details>
  <summary>Featurizer card</summary>

  ```yaml
  # list of authors
  authors: 
    - author 1
  # describe the featurizer 
  description: ~ 
  # which type of input does the featurizer expect ? 
  inputs: ~ 
  # name of the featurizer
  name: ~ 
  # reference of the featurizer (a paper or a link)
  reference: ~ 
  # what does the featurizer return as output for molecular representation ?
  representation: ~ 
  # does the featurizer require 3D information ?
  require_3D:  ~ 
  ```

</details>
